name: rank_hub
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  admonitions: ^1.1.0
  animated_digit: ^3.2.3
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  chart_sparkline: ^1.1.1
  data_table_2: ^2.5.16
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_multiisolate: ^1.3.2
  image: ^4.3.0
  image_gallery_saver_plus: ^3.0.5
  image_picker: ^1.1.2
  marquee: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  multi_select_flutter: ^4.1.3
  multiselect_field: ^1.5.1
  mvvm_plus: ^1.5.4
  opencv_core: ^1.3.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  socks5_proxy: ^2.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
